const images = {
    email: require('../assets/email.png'),
    mobile: require('../assets/mobile.png'),
    api: require('../assets/api.png'),
    cpp: require('../assets/cpp.png'),
    css: require('../assets/css.png'),
    figma: require('../assets/figma.png'),
    flutter: require('../assets/flutter.png'),
    git: require('../assets/git.png'),
    graphql: require('../assets/graphql.png'),
    javascript: require('../assets/javascript.png'),
    html: require('../assets/html.png'),
    mu5: require('../assets/mu5.png'),
    node: require('../assets/node.png'),
    python: require('../assets/python.png'),
    redux: require('../assets/redux.png'),
    react: require('../assets/react.png'),
    typescript: require('../assets/typescript.png'),
    vue: require('../assets/vue.png'),
    sass: require('../assets/sass.png'),
    profile: require('../assets/profile.png'),
    circle: require('../assets/circle.svg').default,
    adidas: require('../assets/adidas.png'),
    amazon: require('../assets/amazon.png'),
    spotify: require('../assets/spotify.png'),
    skype: require('../assets/skype.png'),
    nb: require('../assets/nb.png'),
    bolt: require('../assets/bolt.png'),
    asus: require('../assets/asus.png'),
    about01: require('../assets/about01.png'),
    about02: require('../assets/about02.png'),
    about03: require('../assets/about03.png'),
    about04: require('../assets/about04.png'),
    profile2: require('../assets/profile2.JPG'),
    profile3: require('../assets/profile3.JPG'),
    logo: require('../assets/logo.png'),
    logo1: require('../assets/logo.png'),
    logo2: require('../assets/logo2.JPG'),
    logo3: require('../assets/logo3.JPG'),
    logo4: require('../assets/logo4.JPG'),
    logo4: require('../assets/logo4.JPG'),
    logo4: require('../assets/logo4.JPG'),
    logo4: require('../assets/logo4.JPG'),
    logo4: require('../assets/logo4.JPG'),
    logo4: require('../assets/logo4.JPG'),

}

export default images;